% ===============================================
% Synthetic Aperture Radar Algorithm
% SAR Image Synthesis Algorithm: OmegaK
% Synthetic Data Script - Calibration 
% ===============================================

% ===============================================
% Input Data Section - Provided from file
% ===============================================

% Initial time marker to measure execution time
tic

% Kaiser window parameters and squint angle
kaiser_beta = 2.5;                % Kaiser window roll-off factor
squint_angle = 0.2 * pi / 180;    % Squint angle of 0.2 degrees (converted to radians)

% Radar parameters
PRF = 100;                      % Pulse repetition frequency (Hz)
PRT = 1 / PRF;                  % Pulse repetition time
Fr = 60e6;                      % Sampling frequency (Hz)
f0 = 5.3e9;                     % Radar carrier frequency (Hz)
Kr = 20e12;                     % Chirp pulse FM rate (Hz/s)
Tr = 2.5e-6;                    % Chirp signal duration (s)
azimuth_period = 1 / PRF;       % PRF period

% Physical and mathematical constants
u_imag = sqrt(-1);                % Imaginary unit
c_0 = physconst('lightspeed');    % Speed of light in vacuum (m/s)

% Radar geometry
R0 = 20e3;                             % Slant range at closest approach (m)
Vr = 150;                              % Radar velocity (m/s)
Vs = Vr * 1.06;                        % Target velocity is 6% higher than radar velocity (m/s)
Vg = Vr;                               % Initial radar velocity (m/s)
La = 5;                                % Antenna length (m)
eta_c = -R0 * tan(squint_angle) / Vr;  % Reference time for squint
lambda = c_0 / f0;                     % Wavelength

% Target offsets (in azimuth and range) - Test the code
target_offset_azimuth = [0.0, -0.1, 0.2];        % Displacement in azimuth (s)
target_offset_range = [0.0e-6, -0.4e-6, 0.0e-6]; % Displacement in range (s)

% Control variables initialization
s0_upchirp = 0;                % Upchirp signal control
s0_downchirp = 0;              % Downchirp signal control

% ===============================================
% Input Data Generation: Raw data 
% ===============================================

Naz = 256;                    % Number of samples in azimuth
Nrg = 256;                    % Number of samples in range
data = zeros(Naz, Nrg);       % Data matrix initialization
A0 = 1;                       % Signal amplitude

% Calculates corrected slant range for the squint angle
if squint_angle == 0
    R_eta_c = R0;
else
    R_eta_c = -Vr * eta_c / sin(squint_angle);
end

% Loop over target offsets
for index_offset = 1:length(target_offset_azimuth)
    % Time in azimuth (eta) and range (tau) with offsets
    eta = (((1:Naz) - (Naz / 2)) / PRF)' + eta_c + target_offset_azimuth(index_offset);
    tau = ((1:Nrg) - (Nrg / 2)) / Fr + 2 * R_eta_c / c_0 + target_offset_range(index_offset);
    
    % Slant range distance as a function of eta
    R_eta = sqrt(R0.^2 + (eta * Vr).^2);
    
    % Observation angle (theta) as a function of displacement
    theta = atan((eta - eta_c) * Vr / R0);
    
    % Antenna weighting function in azimuth
    p_a = sinc(0.886 * theta / (0.886 * lambda / La));
    wa = p_a.^2;  % Azimuth weighting
    
    % Windowing function in range
    wr = rect((tau - 2 * R_eta / c_0) / Tr);
    
    % Signal generated by the point target
    s0_upchirp = s0_upchirp + A0 * wr .* wa .* ...
        exp(-1i * 4 * pi * f0 * R_eta / c_0) .* ...
        exp(1i * pi * Kr * (tau - 2 * R_eta / c_0).^2);
end

% Generated raw data
raw_data = s0_upchirp;

% Gets data size
[L, C] = size(raw_data);

% ===============================================
% Data Processing
% The Omega-K implementation begins here
% ===============================================

% Determination of Doppler and time frequencies
% Doppler centroid calculation according to lecture equations
f_doppler_centroid = 2 * Vr * sin(squint_angle) / lambda;

% Fast time (tau) and slow time (eta) vectors
tau_time = 2 * R0 / c_0 + linspace(0, L, L) * 1 / Fr;
eta_time = (1 / PRF) * linspace(-L/2, L/2, L);

% Frequency vectors for azimuth (eta) and range (tau)
tau_freq_vector = linspace(-Fr/2, Fr/2, L);
eta_freq_vector = linspace(-0.5, 0.5, L) * PRF;

% Adjusts raw data to center around f_centroid
% Critical procedure that was incorrect in article [2]
M_eta = repelem(eta_time, length(eta_freq_vector), 1);
raw_data = raw_data .* exp(-1j * 2 * pi * f_doppler_centroid * M_eta');

% 2D Fourier Transform of the data - centering it with fftshift
% For the two-dimensional transform, use fft2.
Signal_2d_frequency = fftshift(fft2(fftshift(raw_data)));

% Application of Kaiser windows in azimuth and range
WindowR_vector = kaiser(L, kaiser_beta)'; % Note the transpose
WindowA_vector = kaiser(L, kaiser_beta);
WindowR = repmat(WindowR_vector, L, 1);
WindowA = repmat(WindowA_vector, 1, L);
Signal_2d_frequency = Signal_2d_frequency .* WindowR .* WindowA;

% Calculates the phase matrix and corrects the distance
% Find Reference distance (Formula given in [2])
Rref = (2 * R0 / c_0 + (L/2) * 1 / Fr) * c_0 / 2;

% Stolt mapping with a new frequency in Range
fr_new_stolt = sqrt((f0 + tau_freq_vector).^2 - ...
    (c_0 * eta_freq_vector' / (2 * Vr)).^2) - f0;

% Find Reference phase matrix according to equations from [1]
theta_ref = (4 * pi * Rref / c_0) * (fr_new_stolt + f0) + ...
    pi * tau_freq_vector.^2 / Kr;

% Adjusts the frequency matrix for Stolt mapping - RFM
% (Reference Function Multiply)
Signal_2d_frequency_post_RFM = Signal_2d_frequency .* exp(1j * theta_ref);

% ===============================================
% Stolt Interpolator (design via sinc function)
% ===============================================

% Initializes matrix for interpolation
Signal_2d_frequency_post_RFM_Stolt = zeros(size(Signal_2d_frequency_post_RFM));

% Parameters for the sinc interpolator
n_sinc = 10;  % Number of points for the sinc window (The larger, the better! But slower)
sinc_range = (-n_sinc:n_sinc); % Samples for the sinc window

% Frequency step of the original vector
delta_f = tau_freq_vector(2) - tau_freq_vector(1);

% Vectorization to interpolate with sinc
for idx = 1:L
    % Target frequencies on the range axis
    target_freq = tau_freq_vector + f0;
    
    % Sinc kernel for each target point
    for jdx = 1:L
        % Current point frequency in the original grid
        source_freq = fr_new_stolt(idx, :) + f0;
        
        % Construction of the difference matrix
        diff_matrix = target_freq(jdx) - source_freq;
        
        % Normalized sinc kernel (acts as a weight vector)
        sinc_kernel = sinc(diff_matrix / delta_f);
        
        % Kernel application and data summation
        Signal_2d_frequency_post_RFM_Stolt(idx, jdx) = ...
            sum(Signal_2d_frequency_post_RFM(idx, :) .* sinc_kernel);
    end
end

% Final Correction
Signal_2d_frequency_post_RFM_Stolt = Signal_2d_frequency_post_RFM_Stolt .* ...
    exp(-1j * 4 * pi * tau_freq_vector * Rref / c_0);

% ===============================================
% SAR Image Reconstruction
% ===============================================

% Transform image back to time domain
s_final = ifftshift(ifft2(Signal_2d_frequency_post_RFM_Stolt));

% ===============================================
% Plotting Results
% ===============================================

% Normalization and display of final processed image
figure;
Final_normalized_image = abs(s_final) / max(max(abs(s_final)));
imshow(Final_normalized_image);
title('Final Processed Signal after Stolt Interpolation');
xlabel('Range');
ylabel('Azimuth');

% Execution time
tfinal = toc;
disp(['Total execution time: ', num2str(tfinal), ' seconds']);

% ===============================================
% Helper Function: rect
% ===============================================

% Function implemented by student Rômulo
function output = rect(input)
    output = 1 * (input.^2 < 0.25); % Rectangular function
end